version: '3'

vars:
  PYTHON_VERSION: 3.11.0
  PYENV_NAME: simonskripnick_editor

tasks:
  # Infrastructure Section

  install:taskfile:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

  install:pyenv:
    cmds:
      - curl https://pyenv.run | bash
      - pyenv install --skip-existing {{ .PYTHON_VERSION }}
      - pyenv virtualenv {{ .PYTHON_VERSION }} {{ .PYENV_NAME }} || true

  install:poetry:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -

  install:nltk:
    cmds:
      - python3 -c 'import nltk; nltk.download("punkt")'


  # Development Section

  install:
    cmds:
      - poetry install

  test:
    cmds:
      - pytest -s -vv
  
  format:
    cmds:
      - isort .
      - black .

  lint:
    cmds:
      - ruff check .


  # Deployment Section

  deploy:build:
    cmds:
      - task: install
      - task: format
      - task: lint
      - task: test

  deploy:start:
    cmds:
      - task: install:nltk
      - uvicorn main:app --host 0.0.0.0 --port $PORT
    dir: ./editor
