version: '3'

vars:
  PYTHON_VERSION: 3.11.0
  PYENV_NAME: simonskripnick_editor

tasks:
  # Infrastructure Section

  install:taskfile:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

  install:pyenv:
    cmds:
      - curl https://pyenv.run | bash
      - pyenv install --skip-existing {{ .PYTHON_VERSION }}
      - pyenv virtualenv {{ .PYTHON_VERSION }} {{ .PYENV_NAME }} || true

  install:poetry:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -


  # Development Section

  install:
    cmds:
      - PYENV_VERSION={{ .PYENV_NAME }} poetry install

  test:
    cmds:
      - pytest -s


  # Deployment Section

  deploy:build:
    cmds:
      - poetry install
      - task: test

  deploy:start:
    cmds:
      - uvicorn main:app --host 0.0.0.0 --port $PORT
