version: '3'

tasks:
  deploy:build:
    cmds:
      - pip install -r requirements.txt
    silent: true

  deploy:start:
    cmds:
      - uvicorn main:app --host 0.0.0.0 --port $PORT
    silent: true
